




*.period=10
*.sink.timeline.plugin.urls=file:///usr/lib/ambari-metrics-hadoop-sink/ambari-metrics-hadoop-sink.jar
*.sink.timeline.class=org.apache.hadoop.metrics2.sink.timeline.HadoopTimelineMetricsSink
*.sink.timeline.period=10
*.sink.timeline.sendInterval=60000
*.sink.timeline.slave.host.name=hadoop1.data.derak.cloud
*.sink.timeline.zookeeper.quorum=hadoop3.data.derak.cloud:2181,hadoop1.data.derak.cloud:2181,hadoop2.data.derak.cloud:2181
*.sink.timeline.protocol=http
*.sink.timeline.port=6188
*.sink.timeline.instanceId = Anbeh
*.sink.timeline.set.instanceId = false
*.sink.timeline.host_in_memory_aggregation = False
*.sink.timeline.host_in_memory_aggregation_port = 61888


# HTTPS properties
*.sink.timeline.truststore.path = /etc/security/clientKeys/all.jks
*.sink.timeline.truststore.type = jks
*.sink.timeline.truststore.password = bigdata

datanode.sink.timeline.collector.hosts=hadoop4.data.derak.cloud
namenode.sink.timeline.collector.hosts=hadoop4.data.derak.cloud
resourcemanager.sink.timeline.collector.hosts=hadoop4.data.derak.cloud
nodemanager.sink.timeline.collector.hosts=hadoop4.data.derak.cloud
jobhistoryserver.sink.timeline.collector.hosts=hadoop4.data.derak.cloud
journalnode.sink.timeline.collector.hosts=hadoop4.data.derak.cloud
maptask.sink.timeline.collector.hosts=hadoop4.data.derak.cloud
reducetask.sink.timeline.collector.hosts=hadoop4.data.derak.cloud
applicationhistoryserver.sink.timeline.collector.hosts=hadoop4.data.derak.cloud

resourcemanager.sink.timeline.tagsForPrefix.yarn=Queue


# Namenode rpc ports customization
namenode.sink.timeline.metric.rpc.client.port=8020




