version: "3"

services:
  ch:
#    image: yandex/clickhouse-server:21.9.5.16
    image: yandex/clickhouse-server:latest
    hostname: clickhouse
    container_name: clickhouse
    ports:
      - 9000:9000
      - 8123:8123
      - 9009:9009
      - 9363:9363
    volumes:
      #      - ./config.xml:/etc/clickhouse-server/config.xml
        #      - ./users.xml:/etc/clickhouse-server/users.xml
      - ./config.d:/etc/clickhouse-server/config.d
      - ./users.d:/etc/clickhouse-server/users.d
      - /clickhouse1:/var/lib/clickhouse-server

      - ch_conf_vol:/var/lib/clickhouse
      - ch_log_vol:/var/log/clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
        - ch_ntw


networks:
  ch_ntw:
    driver: bridge

volumes:
  ch_conf_vol:
  ch_log_vol:
